long f42();
long f6(long x1, long x2, long x3, long x4, long x5, long x6, long x7);
long f7(long x1, long x2, long x3, long x4, long x5, long x6, long x7);
long g1(long x1, long x2, long x3, long x4, long x5, long x6, long x7, long x8, long x9);
long g9(long x1, long x2, long x3, long x4, long x5, long x6, long x7, long x8, long x9);
long f1(long x, long y, long z);
long whileLoop(long x);
long fakultaet(long n);
long fakultaetRecursive(long n);
long fakultaetIt(long n);
long fakultaetAux(long r, long n);
long fakultaetAux1(long r, long n);
long fib(long n);
long main();
